name: scuba
favicon: null
layout_spectrum: 0.7925387148279697
typography_spectrum: 0.10403207154013216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9631856800988317
  lightness: 0.2270368025638163
  saturation: 0.8886661331634969
  rhythmicContrast: 0.48565252125263214
purpose: []
